### ISSUE TITLE
size

### ISSUE THREAD

**Issue by xiangw369** [cyrillkuettel/Libtorch-MobileSAM-Example#1]
Very nice work and sharing, I have run the code you shared, but the image input size is fixed，Not all images can be split

**Comment by cyrillkuettel** [comment]
Thank you. The image will be resized, this is commonly done. I think this `inputSize = 1024` is static. But I'm not 100% sure if [MobileSAM](https://github.com/ChaoningZhang/MobileSAM) supports flexible input size. 

[ByungKwanLee/Full-Segment-Anything](https://github.com/ByungKwanLee/Full-Segment-Anything) addresses these issues, ithas flexible input size.

**Comment by xiangw369** [comment]
![截图 2023-11-14 11-20-11](https://github.com/cyrillkuettel/Libtorch-MobileSAM-Example/assets/77561287/43bace66-4aa5-4212-9416-2408131bd468)

**Comment by cyrillkuettel** [comment]
Each time you call the main(...) function, you're going to get a mask as if it 
was for a single object.


Currently it has limitations: The input points (green circles) have to be set 
[manually](https://github.com/cyrillkuettel/Libtorch-MobileSAM-Example/blob/6b243a13c21d2e542535f93e5056f34fac164bb7/example-app/example-app.cpp#L350C11-L350C11) in the code. 

If you want multiple objects output, you have to call `main` again.

**Comment by cyrillkuettel** [comment]
![MobileSAM1_20231118_113028_471](https://github.com/cyrillkuettel/Libtorch-MobileSAM-Example/assets/36520284/05fdfad3-8686-490e-b4a7-5f97f4df9c8c)

This was a bug. The latest master 78579861505a44375beac947fea9f735e156592d has now fixed a lot of these things. 

- Object oriented code like the original
- Background no longer affected
- Box inputs
- Resize the image to longest side, and pad
- translate input coordinates using [ResizeLongestSide](https://github.com/ChaoningZhang/MobileSAM/blob/12d80d4e32b277de299130d8ce28cc949fb54b6c/mobile_sam/utils/transforms.py#L67)

For multiple boxes, detected automatically, we would have to implement [Automatic Mask Generator](https://github.com/ChaoningZhang/MobileSAM/blob/12d80d4e32b277de299130d8ce28cc949fb54b6c/mobile_sam/automatic_mask_generator.py#L35) and translate it 1:1 from python to C++. This shouldn't be too hard, but I'm not sure I'll find time for this.

**Comment by xiangw369** [comment]
> ![MobileSAM1_20231118_113028_471](https://user-images.githubusercontent.com/36520284/283993462-05fdfad3-8686-490e-b4a7-5f97f4df9c8c.png)
> 
> This was a bug. The latest master [7857986](https://github.com/cyrillkuettel/Libtorch-MobileSAM-Example/commit/78579861505a44375beac947fea9f735e156592d) has now fixed a lot of these things.
> 
>     * Object oriented code like the original
> 
>     * Background no longer affected
> 
>     * Box inputs
> 
>     * Resize the image to longest side, and pad
> 
>     * translate input coordinates using [ResizeLongestSide](https://github.com/ChaoningZhang/MobileSAM/blob/12d80d4e32b277de299130d8ce28cc949fb54b6c/mobile_sam/utils/transforms.py#L67)
> 
> 
> For multiple boxes, detected automatically, we would have to implement [Automatic Mask Generator](https://github.com/ChaoningZhang/MobileSAM/blob/12d80d4e32b277de299130d8ce28cc949fb54b6c/mobile_sam/automatic_mask_generator.py#L35) and translate it 1:1 from python to C++. This shouldn't be too hard, but I'm not sure I'll find time for this.
Really looking forward to this great and beautiful work, thank you very much for your efforts. or Can Tensorrt acceleration be performed?
